/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../flashcard-backend"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['Users']; // Users!
  }
  FlashCard: { // root type
    answer: string; // String!
    id: number; // Int!
    isDone: boolean; // Boolean!
    question: string; // String!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
  Users: { // root type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['Users']; // Users!
  }
  FlashCard: { // field return type
    answer: string; // String!
    flashcardMaker: NexusGenRootTypes['Users'] | null; // Users
    id: number; // Int!
    isDone: boolean; // Boolean!
    question: string; // String!
    title: string; // String!
  }
  Mutation: { // field return type
    Post_flashCardFeed: NexusGenRootTypes['FlashCard']; // FlashCard!
    deleteFlashCard: NexusGenRootTypes['FlashCard']; // FlashCard!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    updateFlashCard: NexusGenRootTypes['FlashCard']; // FlashCard!
  }
  Query: { // field return type
    get_All_Cards: NexusGenRootTypes['FlashCard'][]; // [FlashCard!]!
  }
  Users: { // field return type
    email: string; // String!
    flashCards: NexusGenRootTypes['FlashCard'][]; // [FlashCard!]!
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'Users'
  }
  FlashCard: { // field return type name
    answer: 'String'
    flashcardMaker: 'Users'
    id: 'Int'
    isDone: 'Boolean'
    question: 'String'
    title: 'String'
  }
  Mutation: { // field return type name
    Post_flashCardFeed: 'FlashCard'
    deleteFlashCard: 'FlashCard'
    login: 'AuthPayload'
    signup: 'AuthPayload'
    updateFlashCard: 'FlashCard'
  }
  Query: { // field return type name
    get_All_Cards: 'FlashCard'
  }
  Users: { // field return type name
    email: 'String'
    flashCards: 'FlashCard'
    id: 'Int'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    Post_flashCardFeed: { // args
      answer: string; // String!
      question: string; // String!
      title: string; // String!
    }
    deleteFlashCard: { // args
      id: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    signup: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    updateFlashCard: { // args
      answer?: string | null; // String
      id: number; // Int!
      isDone?: boolean | null; // Boolean
      question?: string | null; // String
      title?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}